---
- name: "ArmA as a Service"
  hosts: all
  connection: local
  vars:
    mod_mount_dir: /media/arma-mount
    lgsm_server_name: "arma3server"
    lgsm_server_file_name: "arma3server"
  roles:
      - { role: lgsm, become: yes }
      - { role: rclone, become: yes }
  tasks:

    - name: Create a directory if it does not exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '755'
        # owner: "{{ emby_user }}"
        # group: "{{ emby_group }}"
      loop:
        - "{{ mod_mount_dir }}"
      become: true